//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeShape.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PathDataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathDataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomeShape.Resource.PathDataResources", typeof(PathDataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M275,238.4v-.7l.2,-.6v-.8l.1,-.8l.2,-.6l.1,-.7l.3,-.6l.3,-.7l.3,-.7l.3,-.6l.3,-.6l.5,-.7l.5,-.4l.4,-.6l.5,-.5l.4,-.4l.6,-.5l.7,-.5l.6,-.4l.6,-.3l.4,-.3l.8,-.3l.6,-.3l.8,-.3l.6,-.2l.7,-.1l.7,-.2l.7,-.2h93.4l.7,.2l.6,.2l.8,.1l.8,.2l.6,.3l.6,.3l.8,.3l.6,.3l.4,.3l.6,.4l.7,.5l.6,.5l.4,.4l.5,.5l.4,.6l.5,.4l.5,.7l.3,.6l.3,.6l.3,.7l.3,.7l.3,.6l.1,.7l.2,.6l.1,.8v.8l.2,.6v55.9l-.2,.8v.6l-.1,.7l-.2,.6l-.1,.8l-.3,.6l-.3,.8l-.3,.6l-.3,.6l-.3,.6l-.5,.6l-.5,.5l-.4,.6l-.5,.5l-.4,.6l-.6,.4l-.7,.5l-.4,.3l-.6,.4l-.6,.4l-.8,.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlternateProcess {
            get {
                return ResourceManager.GetString("AlternateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1302.7,451l16.1,-13.3h64.1v66h-80.2V451Z.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M658.5,543.8H771.2l-56.4,39.3l56.4,39.3H658.5l56.3,-39.3L658.5,543.8Z.
        /// </summary>
        internal static string Collate {
            get {
                return ResourceManager.GetString("Collate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1059.1,450.3l.1,-1.9l.2,-2l.3,-1.9l.4,-1.9l.5,-1.9l.7,-1.8l.7,-1.8l.9,-1.7l1,-1.9l1.1,-1.6l1.2,-1.7l1.3,-1.5l1.3,-1.6l1.6,-1.5l1.6,-1.4l1.7,-1.4l1.7,-1.2l1.8,-1.2l1.9,-1.1l2,-1l1.9,-1l2.2,-.7l2.1,-.8l2.2,-.6l2.2,-.6l2.2,-.5l2.3,-.3l2.3,-.1l2.3,-.3h4.5l2.3,.3l2.3,.1l2.3,.3l2.3,.5l2.2,.6l2.1,.6l2.1,.8l2.2,.7l2,1l1.9,1l1.9,1.1l1.8,1.2l1.8,1.2l1.7,1.4l1.6,1.4l1.5,1.5l1.4,1.6l1.2,1.5l1.2,1.7l1.1,1.6l1,1.7l1,1.9l.7,1.8l.6,1.8l.6,1.9l.3,1.9l.3,1.9l.4,2v3.8l-.4,2l-.3,1.8l-.3,2l-.6,1.8l-.6,1.9l-.7,1.8l-1,1.8l-1,1.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Connector {
            get {
                return ResourceManager.GetString("Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M658.5,327.1L684.4,224.8H788.8L762.7,327.1H658.5Z.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1166,119.6l7.8,-31.2l20.5,-19.2h25.2l20.4,19.2l7.8,31.2l-7.8,31l-20.4,19.1h-25.2l-20.5,-19.1l-7.8,-31Z.
        /// </summary>
        internal static string Decagon {
            get {
                return ResourceManager.GetString("Decagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M444.7,264.9l69.1,-44.8L583,264.9l-69.2,44.7L444.7,264.9Z.
        /// </summary>
        internal static string Decision {
            get {
                return ResourceManager.GetString("Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M70.7,664.8h85l4.1,.2l4.1,.3l4,.5l4,.6l3.9,.7l3.9,.8l3.8,.9l3.8,1.1l3.7,1.2l3.3,1.4l3.5,1.4l3.3,1.3l3.2,1.7l3,1.7l2.9,1.8l2.8,1.9l2.6,1.9l2.4,2.2l2.3,2.1l2,2.2l2,2.3l1.7,2.2l1.5,2.3l1.4,2.5l1,2.4l.9,2.5l.8,2.6l.5,2.6l.3,2.4l.1,2.6l-.1,2.5l-.3,2.6l-.5,2.5l-.8,2.5l-.9,2.4l-1,2.5l-1.4,2.4L226,735l-1.7,2.3l-2,2.1l-2,2.3l-2.3,2.1l-2.4,2l-2.6,2l-2.8,1.8l-2.9,1.9l-3,1.7l-3.2,1.6l-3.3,1.6l-3.5,1.3L191,759l-3.7,1.2l-3.8,1l-3.8,1l-3.9,.9l-3.9,.6l-4,.6l-4,.5l-4.1,.3l-4.1,.3h-85V664.8Z.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M606.5,111.6l66,-42.3l66,42.3l-66,42.5l-66,-42.5Z.
        /// </summary>
        internal static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M716.8,664.8h58.4l.8,.2l.6,.2l.7,.4l.6,.5l.8,.4l.8,.6l.6,.8l.6,.8l.8,.9l.6,1.1l.6,1l.4,1.1l.7,1.2l.6,1.4l.4,1.4l.5,1.3l.4,1.6l.5,1.6l.5,1.6l.3,1.7l.3,1.6l.3,1.9l.3,1.8l.3,1.8l.1,1.9l.2,2l.1,1.8v2l.2,2v3.8l-.2,2v2l-.1,1.8l-.2,2l-.1,1.8l-.3,1.8l-.3,1.9l-.3,1.8L787,722l-.3,1.7l-.5,1.6l-.5,1.6l-.4,1.5l-.5,1.4l-.4,1.4l-.6,1.3l-.7,1.2l-.4,1.3l-.6,.9l-.6,1.1l-.8,.9l-.6,.7l-.6,.8l-.8,.6l-.8,.6l-.6,.5l-.7,.3l-.6,.1l-.8,.2l-.8,.1H716.8l-.7,-.1l-.8,-.2l-.8,-.1l-.6,-.3l-.7,-.5l-.6,-.6l-.8,-.6l-.8,-.8l-.6,-.7l-.6,-.9l-. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DirectAccessStorage {
            get {
                return ResourceManager.GetString("DirectAccessStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M845.6,685.2l13.8,-40.8h55.9l.8,.3l.6,.1l.7,.3l.6,.6l.8,.5l.6,.8l.6,.7l.6,.8l.7,1.1l.6,1l.6,1.1l.6,1.2l.4,1.3l.7,1.5l.4,1.4l.5,1.5l.4,1.7l.5,1.6l.3,1.7l.4,1.9l.4,1.8l.3,1.8l.1,1.9l.3,1.9l.2,2.2l.1,2l.2,2V681l.1,2.2v4.1l-.1,2v2.1l-.2,2l-.1,2l-.2,2l-.3,2l-.1,2l-.3,1.8l-.4,1.8l-.4,1.9l-.3,1.6l-.5,1.7l-.4,1.5l-.5,1.7l-.4,1.4l-.7,1.4l-.4,1.4l-.6,1.2l-.6,1l-.6,1.1l-.7,1.1l-.6,.7l-.6,.8l-.6,.8l-.8,.4l-.6,.5l-.7,.5l-.6,.1l-.8,.2l-.6,.1H859.4L845.6,685.2Z.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1195.8,275.9h132v97.6c-66,0,-66,37.3,-132,16V275.9Z.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M70.7,98.3V95.4L71,92.7l.7,-2.9L72.4,87l.9,-2.7l1.1,-2.8l1.4,-2.6l1.5,-2.6L79,73.7l1.8,-2.5L83,68.9l2.2,-2.5l2.3,-2.3L90.1,62L93,59.8l2.9,-1.9L98.8,56l3.3,-1.8l3.3,-1.7L108.8,51l3.5,-1.5L116,48.2L119.6,47l3.8,-1.1l4,-.9l4,-.7l4,-.6l3.9,-.5l4.2,-.5l3.9,-.1h8.4l4.3,.1l4.1,.5l4.2,.5l4.1,.7l4.1,.8l4,1l4,1.1l3.8,1.2l3.6,1.4l3.7,1.5l3.5,1.7l3.2,1.9l3.2,1.8l3.2,2l3,2.1l2.7,2.3l2.6,2.3l2.3,2.4l2.3,2.5l2,2.6l1.8,2.6l1.7,2.7l1.4,2.8l1.2,2.7l.9,2.8l.8,2.9l.6,2.9l.3,2.9l.1,2.9l-.1,2.9l-.3,3.1l-.6,2.7l-.8,2.9l-1.1,2.9l- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ellipse {
            get {
                return ResourceManager.GetString("Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1029.3,675.8l13,-23.6l-1.4,21.7l14.8,-3.6l-6,11.7l15.5,3.3l-12.3,9.6l14.1,11.5l-16.7,-1.5l4.6,21.1l-14.5,-14.9l-2.6,21.6L1028.3,713l-7.1,27.2l-2.8,-24.3l-10.2,8.1l3,-15L992,711.6l12.5,-11.5l-13,-12.8l16.2,-4.1l-15,-21.7L1017,678l3.7,-16.5l8.6,14.3Z.
        /// </summary>
        internal static string Explosion1 {
            get {
                return ResourceManager.GetString("Explosion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1186.6,696.6l15.8,-11.4l-1.3,15.1l16.2,-6.7l-7.5,8.7l24.5,.3l-21.7,7.2l6.1,5l-8.9,2.6l11.7,8.7l-19.9,-3.4l1.4,8l-12.9,-3.8l-2.7,7.6l-8.1,-3.8l-5.5,6.1l-5.5,-4.1l-12.2,9.1l-.6,-8.8L1139,731.9l9.6,-6.4L1133,718.9l18.3,-3.3l-13,-8.7l19.8,-1.3l-4,-11L1173,702l5.5,-11.8l8.1,6.4Z.
        /// </summary>
        internal static string Explosion2 {
            get {
                return ResourceManager.GetString("Explosion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1015.1,633.4l38.5,-78.6l38.5,78.6h-77Z.
        /// </summary>
        internal static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1015.1,154.4l8.7,-38.9l35.3,-17.2l35.2,17.2l8.8,38.9l-24.3,31.2h-M1015.1,154.4l8.7,-38.9l35.3,-17.2l35.2,17.2l8.8,38.9l-24.3,31.2h-39.3l-24.4,-31.2Z.
        /// </summary>
        internal static string Heptagon {
            get {
                return ResourceManager.GetString("Heptagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1037.1,264.9h110v84h-110v-84Z.
        /// </summary>
        internal static string InternalStorage {
            get {
                return ResourceManager.GetString("InternalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M535.8,697.2l.1,-.6l.2,-.7l.3,-.7l.5,-.7l.6,-.6l.7,-.6l.8,-.8l1.1,-.6l.9,-.6l1.2,-.6l1.4,-.6l1.4,-.7l1.5,-.4l1.7,-.6l1.6,-.5l1.9,-.4l2,-.5l2,-.5l1.9,-.4l2.3,-.3l2.2,-.5l2.3,-.3l2.4,-.3l2.5,-.1l2.2,-.4l2.6,-.1l2.5,-.2l2.6,-.1h2.6l2.6,-.2h5.2l2.4,.2h2.6l2.6,.1l2.5,.2l2.6,.1l2.2,.4l2.5,.1l2.4,.3l2.3,.3l2.2,.5l2.3,.3l1.9,.4l2,.5l2,.5l1.8,.4l1.7,.5l1.7,.6l1.5,.4l1.4,.7l1.4,.6l1.2,.6l1.1,.6l.9,.6l.8,.8l.7,.6l.6,.6l.5,.7l.3,.7l.1,.7l.2,.6v54.6l-.2,.6l-.1,.8l-.3,.6l-.5,.7l-.6,.6l-.7,.6l-.8,.8l-.9,.6l-1.1,.6l-1.2,.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MagneticDisk {
            get {
                return ResourceManager.GetString("MagneticDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M723.7,441.3l95,-11.4v57.3h-95V441.3Z.
        /// </summary>
        internal static string ManualInput {
            get {
                return ResourceManager.GetString("ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M895.7,408.6h119.4l-23.9,88H919.6l-23.9,-88Z.
        /// </summary>
        internal static string ManualOperation {
            get {
                return ResourceManager.GetString("ManualOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1117.3,539.1h89.5L1162,633.4l-44.7,-94.3Z.
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M50.3,472.7c58.5,11.9,58.5,-11.8,117,-11.8V399.3H50.3v73.4Zm9.6,-73.4v-7.9H176.2v61.8c-4.5,0,-8.9,.5,-8.9,.5V399.3H59.9Zm9,-7.9v-7.8H186.2v61.7c-5,0,-10,.3,-10,.3V391.4H68.9Z.
        /// </summary>
        internal static string Multidocument {
            get {
                return ResourceManager.GetString("Multidocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1206.8,452.6h55v57.9l-27.5,14.4l-27.5,-14.4V452.6Z.
        /// </summary>
        internal static string OffpageConnector {
            get {
                return ResourceManager.GetString("OffpageConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M407,582.3l.2,-1.9l.1,-2l.5,-2l.6,-1.8l.9,-2l.9,-1.9l1.2,-1.8l1.3,-1.8l1.5,-1.7l1.7,-1.8l1.8,-1.7l2,-1.6l2,-1.6l2.3,-1.6l2.4,-1.3l2.4,-1.4l2.8,-1.2l2.7,-1.4l3,-1.1l2.9,-1l3.2,-1.1l3.2,-.9l3.2,-.8l3.3,-.8l3.4,-.6l3.4,-.4l3.5,-.5l3.5,-.4l3.5,-.2l3.7,-.2h7.2l3.6,.2l3.7,.3l3.7,.3l3.6,.5l3.5,.6l3.5,.6l3.4,.8l3.4,.9l3.2,.9l3,1.1l3.1,1.2l3,1.2l2.8,1.2l2.7,1.4l2.5,1.5l2.4,1.6l2.3,1.5l2,1.7l2,1.6l1.8,1.9l1.6,1.8l1.3,1.8l1.3,2l1,1.9l.9,1.9l.7,2l.6,2l.3,2v2l-.2,2.1l-.3,2l-.4,2l-.7,2l-.9,2l-1,1.8l-1.3,1.8l-1.3,2l-1.7,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M871.3,238.9H991.5V350.4H871.3V238.9Z.
        /// </summary>
        internal static string PredefinedProcess {
            get {
                return ResourceManager.GetString("PredefinedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M471.5,455.1l30.7,-41.7h92.1L625,455.1l-30.7,41.5H502.2L471.5,455.1Z.
        /// </summary>
        internal static string Preparation {
            get {
                return ResourceManager.GetString("Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0,0 L10,0 10,10 0,10z.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M6.3,552.7v.5l.1,.4l.3,.5l.3,.4l.3,.5l.6,.5l.7,.3l.6,.4l.7,.5l.9,.3l1,.4l.9,.3l1.2,.5l1.1,.3l1.2,.3l1.4,.3l1.3,.3l1.4,.3l1.5,.3l1.6,.3l1.5,.2l1.7,.2l1.7,.3l1.6,.1l1.7,.2h1.9l1.8,.1l1.8,.2h11l1.9,-.2l1.6,-.1h1.9l1.7,-.2l1.6,-.1l1.7,-.3l1.7,-.2l1.7,-.2l1.4,-.3l1.5,-.3l1.5,-.3l1.2,-.3l1.4,-.3l1.2,-.3l1.2,-.3l1.1,-.5l.9,-.3l1.1,-.4l.8,-.3l.7,-.5l.8,-.4l.6,-.3l.5,-.5l.4,-.5l.3,-.4l.2,-.5l.1,-.4v-.5l.2,-.5l.1,-.4l.2,-.5l.3,-.4l.5,-.5l.4,-.4l.6,-.3l.8,-.5l.8,-.5l.7,-.3l.9,-.4l1.1,-.3l1.1,-.5l1.2,-.3l1.2,-.3l1.2,-. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PunchedTape {
            get {
                return ResourceManager.GetString("PunchedTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0,0 L10,0 10,10 0,10z .
        /// </summary>
        internal static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M818.7,93.8L871.3,56.6L924,93.8L903.8,154h-65L818.7,93.8Z.
        /// </summary>
        internal static string RegularPentagon {
            get {
                return ResourceManager.GetString("RegularPentagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M330,154.1V42.6L484,154.1H330Z.
        /// </summary>
        internal static string RightTriangle {
            get {
                return ResourceManager.GetString("RightTriangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M375.5,765.4h-2.6l-2.6,-.3l-2.4,-.3l-2.5,-.3l-2.6,-.5l-2.2,-.6l-2.5,-.8l-2.4,-.7l-2.3,-1l-2.2,-1l-2.3,-1.1L347,757.6l-2.2,-1.4L343,754.8l-1.8,-1.3l-1.9,-1.7l-1.7,-1.6l-1.5,-1.6l-1.4,-1.9l-1.3,-1.8l-1.3,-1.8l-1,-2L330,739.2l-.8,-2.1l-.7,-2l-.6,-2.1l-.5,-2.2l-.3,-1.9l-.2,-2.2l-.1,-2.1l.1,-2.2l.2,-2.1l.3,-2.1l.5,-2.2l.6,-2l.7,-2.1l.8,-2l1.1,-2l1,-2l1.3,-1.8l1.2,-1.8l1.5,-1.7l1.5,-1.7l1.7,-1.7l1.7,-1.5l1.8,-1.5l2,-1.4l2,-1.2l2.1,-1.2l2.2,-1.3l2.3,-.9l2.3,-.9l2.3,-.9l2.4,-.6l2.4,-.6l2.5,-.6l2.6,-.4l2.4,-.3l2.6,- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SequentialAccessStorage {
            get {
                return ResourceManager.GetString("SequentialAccessStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M818.7,588.6L887,543.8l68.5,44.8L887,633.4L818.7,588.6Z.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1263.5,551.6h79.3h-.8l-.8,.3l-.7,.2l-.9,.5l-.8,.4l-.8,.5l-.7,.7l-.8,.8l-.8,.8l-.6,1l-.7,1.1l-.6,1.1l-.7,1.2l-.6,1.4l-.6,1.3l-.6,1.4l-.5,1.5l-.6,1.7l-.4,1.7l-.5,1.7l-.3,1.8l-.4,1.9l-.3,1.8l-.4,2l-.3,2l-.1,1.9l-.2,2l-.1,2l-.2,2.2v8.1l.2,2.1l.1,2l.2,2l.1,2l.3,1.9l.4,2l.3,1.9l.4,1.8l.3,1.8l.5,1.7l.4,1.7l.6,1.7l.5,1.5l.6,1.4l.6,1.3l.6,1.4l.7,1.2l.6,1.1l.7,1.1l.6,1l.8,.8l.8,.8l.7,.7l.8,.5l.8,.5l.9,.4l.7,.2l.8,.3h.8h-80.1l-.8,-.3l-.7,-.2l-.8,-.4l-.7,-.5l-1,-.5l-.7,-.7l-.6,-.8l-.8,-.8l-.8,-1l-.6,-1.1l-.7,-1.1l-.7, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoredData {
            get {
                return ResourceManager.GetString("StoredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M232.5,575.2v-1.9l.3,-1.8l.3,-1.8l.5,-2l.6,-1.9L235,564l.9,-1.7l1.1,-1.8l1,-1.7l1.3,-1.7l1.3,-1.5l1.6,-1.5l1.6,-1.5l1.7,-1.6l1.8,-1.3l2,-1.3l2,-1.2l2.2,-1.2l2.1,-1.1l2.1,-.9l2.5,-.9l2.3,-.9l2.6,-.6l2.4,-.7l2.5,-.6l2.6,-.4l2.6,-.3l2.7,-.3l2.6,-.2h5.3l2.6,.2l2.6,.3l2.6,.3l2.6,.4l2.6,.6l2.5,.7l2.4,.6l2.5,.9l2.3,.9l2.2,.9l2.2,1.1l2.1,1.2l2,1.2l2,1.3l1.8,1.3l1.7,1.6l1.5,1.5l1.6,1.5l1.3,1.5l1.4,1.7l1.1,1.7l1.1,1.8l.9,1.7l.6,1.8l.6,1.9l.6,2l.3,1.8l.2,1.8l.1,1.9l-.1,2l-.2,1.8l-.3,1.8l-.6,1.9l-.6,1.9l-.6,1.9l-.9,1.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SummingJunction {
            get {
                return ResourceManager.GetString("SummingJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M282,408.6h90.6l1.1,.2l1.1,.1l1,.3l1.1,.4l1.1,.4l.9,.5l1.1,.6l.9,.6l.9,.6l.9,.8l.9,.7l.9,.9l.8,1l.9,1l.6,1l.8,1.2l.8,1l.6,1.3l.6,1.2l.4,1.2l.7,1.4l.3,1.2l.4,1.4l.5,1.4l.1,1.5l.3,1.4l.2,1.3l.1,1.6v1.5l.2,1.4l-.2,1.5v1.5l-.1,1.4l-.2,1.5L392,445l-.1,1.4l-.5,1.3l-.4,1.6l-.3,1.2l-.7,1.4l-.4,1.2l-.6,1.2l-.6,1.2l-.8,1.1l-.8,1.1l-.6,1l-.9,1.1l-.8,.9l-.9,1l-.9,.7l-.9,.8l-.9,.6l-.9,.6l-1.1,.6l-.9,.5l-1.1,.4l-1.1,.3l-1,.2l-1.1,.3h-1.1l-1,.1H282l-1,-.1h-1.1l-1.1,-.3l-1,-.2l-1.1,-.3l-1.1,-.4l-.9,-.5l-1.1,-.6l-.9,-.6l-1. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Terminator {
            get {
                return ResourceManager.GetString("Terminator", resourceCulture);
            }
        }
    }
}
